/**
 * @since 1.0.0
 */
import * as Effect from 'effect/Effect'

/**
 * Emit final TypeScript code with file header
 *
 * @since 1.0.0
 * @category Generation
 */
export const emit = (code: string,): Effect.Effect<string> =>
  Effect.sync(() => {
    const header = [
      '/**',
      ' * Generated by @effect/openapi-server-gen',
      ' *',
      ' * DO NOT EDIT THIS FILE MANUALLY',
      ' *',
      ' * This file was automatically generated from an OpenAPI specification.',
      ' * To regenerate, run the generator again with your OpenAPI spec.',
      ' */',
    ].join('\n',)

    return `${header}\n\n${code}\n`
  },)
