/**
 * Generated by @davigoli/openapi-server-gen
 *
 * DO NOT EDIT THIS FILE MANUALLY
 *
 * This file was automatically generated from an OpenAPI specification.
 * To regenerate, run the generator again with your OpenAPI spec.
 */

import * as HttpApi from '@effect/platform/HttpApi'
import * as HttpApiEndpoint from '@effect/platform/HttpApiEndpoint'
import * as HttpApiGroup from '@effect/platform/HttpApiGroup'
import * as HttpApiSchema from '@effect/platform/HttpApiSchema'
import * as Schema from 'effect/Schema'

/**
 * Server URLs
 *
 * - http://localhost:3000/api - Local development server
 *
 * Base path: /api
 */

// Schema definitions from components/schemas

export const TodoSchema = Schema.Struct({
  /** Unique identifier for the todo */
  id: Schema.String.annotations({ description: 'Unique identifier for the todo' }),
  /** The todo item title */
  title: Schema.String.annotations({ description: 'The todo item title' }),
  /** Whether the todo is completed */
  completed: Schema.Boolean.annotations({ description: 'Whether the todo is completed' }),
  /** When the todo was created */
  createdAt: Schema.optional(Schema.String.annotations({ description: 'When the todo was created' })),
})

export const CreateTodoRequestSchema = Schema.Struct({
  /** The todo item title */
  title: Schema.String.pipe(Schema.minLength(1), Schema.maxLength(200)).annotations({
    description: 'The todo item title',
  }),
  completed: Schema.optional(Schema.Boolean),
})

export const UpdateTodoRequestSchema = Schema.Struct({
  title: Schema.optional(Schema.String.pipe(Schema.minLength(1), Schema.maxLength(200))),
  completed: Schema.optional(Schema.Boolean),
})

export const ErrorSchema = Schema.Struct({
  message: Schema.optional(Schema.String),
  code: Schema.optional(Schema.String),
})

/**
 * A simple Todo list API
 *
 * @version 1.0.0
 */
/**
 * List all todos
 */
export const listTodos = HttpApiEndpoint.get('listTodos', '/todos')
  .setUrlParams(
    Schema.Struct({
      completed: Schema.optional(Schema.BooleanFromString),
    })
  )
  .addSuccess(Schema.Array(TodoSchema))

/**
 * Create a new todo
 */
export const createTodo = HttpApiEndpoint.post('createTodo', '/todos')
  .setPayload(CreateTodoRequestSchema)
  .addSuccess(TodoSchema, { status: 201 })
  .addError(ErrorSchema, { status: 400 })

const getTodo_idParam = HttpApiSchema.param('id', Schema.String)

/**
 * Get a todo by ID
 */
export const getTodo = HttpApiEndpoint.get('getTodo')`/todos/${getTodo_idParam}`
  .addSuccess(TodoSchema)
  .addError(ErrorSchema, { status: 404 })

const updateTodo_idParam = HttpApiSchema.param('id', Schema.String)

/**
 * Update a todo
 */
export const updateTodo = HttpApiEndpoint.patch('updateTodo')`/todos/${updateTodo_idParam}`
  .setPayload(UpdateTodoRequestSchema)
  .addSuccess(TodoSchema)
  .addError(ErrorSchema, { status: 404 })

const deleteTodo_idParam = HttpApiSchema.param('id', Schema.String)

/**
 * Delete a todo
 */
export const deleteTodo = HttpApiEndpoint.del('deleteTodo')`/todos/${deleteTodo_idParam}`.addError(ErrorSchema, {
  status: 404,
})

export const todosGroup = HttpApiGroup.make('Todos')
  .add(listTodos)
  .add(createTodo)
  .add(getTodo)
  .add(updateTodo)
  .add(deleteTodo)

export const TodoAPI = HttpApi.make('TodoAPI').add(todosGroup)
